class PreparedTransform:
    @property
    def css(self) -> str: ...
    @property
    def candidates(self) -> list[str]: ...
    @property
    def tailwind_module_url(self) -> str: ...

class TailwindCssTransformer:
    def __init__(self, root: str) -> None: ...
    def prepare(self, code: str, module_id: str) -> PreparedTransform: ...
