from collections.abc import Sequence
from typing import Self

class Plugin:
    def __init__(self, *, name: str | None = None, id: str | None = None) -> None: ...  # noqa: A002
    @property
    def name(self) -> str: ...
    @property
    def id(self) -> str: ...

class Bundler:
    def __new__(
        cls,
        *,
        cwd: object | None = None,
        resolve: object | None = None,
        devtools: object | None = None,
        output: object | None = None,
        plugins: Sequence[Plugin] | None = None,
        platform: object | None = None,
        context: object | None = None,
        tsconfig: object | None = None,
        shim_missing_exports: object | None = None,
        keep_names: object | None = None,
        profiler_names: object | None = None,
        define: object | None = None,
        drop_labels: object | None = None,
        inject: object | None = None,
        external: object | None = None,
        treeshake: object | None = None,
        manual_code_splitting: object | None = None,
    ) -> Self: ...
    def __call__(self, *, write: bool | None = None, watch: bool | None = None) -> BundlerContext: ...

class BundlerContext:
    def __new__(cls, bundler: Bundler, /) -> Self: ...
    def __init__(self, bundler: Bundler, /) -> None: ...
    def _ensure_inactive(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> None: ...
    async def __aenter__(self) -> AsyncBundlerContext: ...
    async def __aexit__(self, exc_type: object, exc_value: object, traceback: object) -> None: ...
    def __call__(
        self,
        input: object,  # noqa: A002
        output: object | None = None,
        /,
        *,
        write: bool | None = None,
    ) -> BundlerOutput: ...

class AsyncBundlerContext:
    def __new__(
        cls,
        bundler: Bundler,
        /,
        *,
        write: bool | None = None,
        watch: bool | None = None,
    ) -> Self: ...
    def __init__(
        self,
        bundler: Bundler,
        /,
        *,
        write: bool | None = None,
        watch: bool | None = None,
    ) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type: object, exc_value: object, traceback: object) -> None: ...
    async def __call__(
        self,
        input: object,  # noqa: A002
        output: object | None = None,
        /,
        *,
        write: bool | None = None,
        watch: bool | None = None,
        watch_files: Sequence[object] | None = None,
    ) -> BundlerOutput: ...
    async def wait_for_rebuild(self) -> BundlerOutput: ...
    async def set_watch_files(self, watch_files: Sequence[object]) -> None: ...

class OutputChunk:
    @property
    def name(self) -> str: ...
    @property
    def file_name(self) -> str: ...
    @property
    def code(self) -> str: ...
    @property
    def is_entry(self) -> bool: ...
    @property
    def is_dynamic_entry(self) -> bool: ...
    @property
    def facade_module_id(self) -> str | None: ...
    @property
    def module_ids(self) -> list[str]: ...
    @property
    def exports(self) -> list[str]: ...
    @property
    def imports(self) -> list[str]: ...
    @property
    def dynamic_imports(self) -> list[str]: ...
    @property
    def sourcemap(self) -> str | None: ...
    @property
    def sourcemap_file_name(self) -> str | None: ...
    @property
    def preliminary_file_name(self) -> str: ...

class OutputAsset:
    @property
    def file_name(self) -> str: ...
    @property
    def names(self) -> list[str]: ...
    @property
    def original_file_names(self) -> list[str]: ...
    @property
    def source(self) -> str | bytes: ...

class BundlerOutput:
    @property
    def chunks(self) -> list[OutputChunk]: ...
    @property
    def assets(self) -> list[OutputAsset]: ...
    @property
    def warnings(self) -> list[str]: ...
