from __future__ import annotations

from collections.abc import Callable, Iterable, Sequence
from dataclasses import dataclass
from inspect import Signature, signature
from json import dumps
from pathlib import PurePosixPath
from re import findall, match
from shutil import rmtree
from types import NoneType, UnionType
from typing import TYPE_CHECKING, Annotated, Any, Literal, Union, cast, get_args, get_origin

from pydantic import BaseModel, ConfigDict, Field, create_model
from starlette.responses import Response

from gdansk.inertia.props import Defer, OptionalProp, Prop

if TYPE_CHECKING:
    from pathlib import Path

    from pydantic.fields import FieldInfo

type JsonSchema = dict[str, Any]

_TYPE_HEADER = "/* This file is generated by Gdansk. Do not edit. */"
_TS_RESERVED_WORDS = frozenset(
    {
        "break",
        "case",
        "catch",
        "class",
        "const",
        "continue",
        "debugger",
        "default",
        "delete",
        "do",
        "else",
        "export",
        "extends",
        "false",
        "finally",
        "for",
        "function",
        "if",
        "import",
        "in",
        "instanceof",
        "new",
        "null",
        "return",
        "super",
        "switch",
        "this",
        "throw",
        "true",
        "try",
        "typeof",
        "var",
        "void",
        "while",
        "with",
    },
)


@dataclass(slots=True, kw_only=True, frozen=True)
class PageTypeRoute:
    component: str | None
    endpoint: Callable[..., object]
    props_model: type[BaseModel] | None
    shared_model: type[BaseModel] | None


@dataclass(slots=True, kw_only=True, frozen=True)
class ResolvedPageTypeRoute:
    component: str
    props_model: type[BaseModel] | None
    shared_model: type[BaseModel] | None


@dataclass(slots=True, kw_only=True, frozen=True)
class PagePropField:
    annotation: object
    key: str
    required: bool


def normalize_page_props_model(model: type[BaseModel] | None, *, name: str) -> type[BaseModel] | None:
    if model is None:
        return None

    if not isinstance(model, type) or not issubclass(model, BaseModel):
        msg = f"The Inertia {name} props model must be a pydantic BaseModel subclass"
        raise TypeError(msg)

    return model


def infer_page_props_model(func: Callable[..., object]) -> type[BaseModel] | None:
    annotation = _return_annotation(func)
    models = _annotation_model_types(annotation)

    if len(models) > 1:
        names = ", ".join(model.__name__ for model in models)
        msg = f"Inertia page route {_callable_name(func)} has multiple pydantic return models ({names}); pass props=..."
        raise TypeError(msg)

    return models[0] if models else None


def write_page_type_modules(
    *,
    app: object,
    output_root: Path,
    routes: Sequence[PageTypeRoute],
    shared_props_model: type[BaseModel] | None,
    legacy_output_path: Path | None = None,
) -> None:
    modules = build_page_type_modules(app=app, routes=routes, shared_props_model=shared_props_model)

    _remove_generated_path(output_root)
    if legacy_output_path is not None:
        legacy_output_path.unlink(missing_ok=True)

    for relative_path, source in modules.items():
        output_path = output_root / relative_path
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(source, encoding="utf-8")


def build_page_type_modules(
    *,
    app: object,
    routes: Sequence[PageTypeRoute],
    shared_props_model: type[BaseModel] | None,
) -> dict[PurePosixPath, str]:
    resolved = _resolve_page_type_routes(app=app, routes=routes)
    schemas_by_component = _component_schemas(resolved, shared_props_model=shared_props_model)

    return {
        _component_module_path(component): _page_type_module_source(component=component, schemas=schemas)
        for component, schemas in schemas_by_component.items()
    }


def _remove_generated_path(path: Path) -> None:
    if path.is_symlink() or path.is_file():
        path.unlink()
        return

    if path.exists():
        rmtree(path)


def _component_module_path(component: str) -> PurePosixPath:
    if component == "/":
        return PurePosixPath("index.ts")

    return PurePosixPath(f"{component}.ts")


def _page_type_module_source(*, component: str, schemas: Sequence[JsonSchema]) -> str:
    type_name = _page_props_type_name(component)
    raw_schema = _component_json_schema(schemas)

    return "\n".join(
        (
            _TYPE_HEADER,
            'import { z } from "@gdansk/vite/zod";',
            "",
            f"const rawPageSchema: unknown = {_json_source(raw_schema)};",
            "",
            "export const pageSchema = z.fromJSONSchema(rawPageSchema as Parameters<typeof z.fromJSONSchema>[0]);",
            "",
            f"export function parsePageProps(props: unknown): {type_name} {{",
            f"  return pageSchema.parse(props) as {type_name};",
            "}",
            "",
            f"export type {type_name} = {_component_ts_type(schemas)};",
            "",
        ),
    )


def _page_props_type_name(component: str) -> str:
    if component == "/":
        return "RootPageProps"

    words = [word for part in component.split("/") for word in findall(r"[0-9A-Za-z]+", part)]
    parts = [_pascal_case_word(word) for word in words] or ["Route"]
    if parts[-1] == "Page":
        parts.pop()

    name = "".join(parts)
    if not name:
        return "PageProps"

    if name[0].isdigit():
        name = f"Route{name}"

    return f"{name}PageProps"


def _pascal_case_word(word: str) -> str:
    return f"{word[0].upper()}{word[1:]}" if word else ""


def _return_annotation(func: Callable[..., object]) -> object:
    try:
        return signature(func, eval_str=True).return_annotation
    except (NameError, TypeError, ValueError):
        return Signature.empty


def _callable_name(func: Callable[..., object]) -> str:
    name = getattr(func, "__name__", None)
    return name if isinstance(name, str) else type(func).__name__


def _annotation_model_types(annotation: object) -> tuple[type[BaseModel], ...]:
    annotation = _strip_annotated(annotation)

    if annotation in {Signature.empty, None, NoneType}:
        return ()

    if _is_union_annotation(annotation):
        models: list[type[BaseModel]] = []
        for arg in get_args(annotation):
            models.extend(_annotation_model_types(arg))
        return tuple(dict.fromkeys(models))

    origin = get_origin(annotation)
    if origin is not None:
        return ()

    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return (annotation,)

    if isinstance(annotation, type) and issubclass(annotation, Response):
        return ()

    return ()


def _resolve_page_type_routes(*, app: object, routes: Sequence[PageTypeRoute]) -> list[ResolvedPageTypeRoute]:
    by_endpoint = {route.endpoint: route for route in routes}
    resolved: list[ResolvedPageTypeRoute] = []
    matched: set[Callable[..., object]] = set()

    for endpoint, route_path in _iter_app_route_endpoints(app):
        route = by_endpoint.get(endpoint)
        if route is None:
            continue

        matched.add(route.endpoint)
        component = route.component or _normalize_component(route_path)
        resolved.append(
            ResolvedPageTypeRoute(
                component=component,
                props_model=route.props_model,
                shared_model=route.shared_model,
            ),
        )

    unmatched = [
        _callable_name(route.endpoint) for route in routes if route.endpoint not in matched and route.component is None
    ]
    if unmatched:
        names = ", ".join(sorted(unmatched))
        msg = f"Could not resolve implicit Inertia component names for page route(s): {names}"
        raise RuntimeError(msg)

    return resolved


def _iter_app_route_endpoints(app: object) -> Iterable[tuple[Callable[..., object], str]]:
    yield from _iter_routes(getattr(app, "routes", ()), prefix="")


def _iter_routes(routes: object, *, prefix: str) -> Iterable[tuple[Callable[..., object], str]]:
    if not isinstance(routes, Iterable):
        return

    for route in routes:
        route_path = getattr(route, "path", "")
        full_path = _join_route_paths(prefix, route_path) if isinstance(route_path, str) else prefix
        endpoint = getattr(route, "endpoint", None)

        if callable(endpoint):
            yield cast("Callable[..., object]", endpoint), full_path or "/"

        nested_routes = getattr(route, "routes", None)
        if nested_routes is not None:
            yield from _iter_routes(nested_routes, prefix=full_path)


def _join_route_paths(prefix: str, path: str) -> str:
    if not prefix:
        return path or "/"

    if not path or path == "/":
        return prefix

    return f"{prefix.rstrip('/')}/{path.lstrip('/')}"


def _normalize_component(component: str) -> str:
    if not (cleaned := component.strip()):
        msg = "The Inertia component must not be empty"
        raise ValueError(msg)

    if cleaned == "/":
        return cleaned

    normalized = cleaned.strip("/")
    if not normalized:
        return "/"

    parts = normalized.split("/")
    if any(part in {"", ".", ".."} for part in parts):
        msg = "The Inertia component must be '/' or a relative path without traversal segments"
        raise ValueError(msg)

    return "/".join(parts)


def _component_schemas(
    routes: Sequence[ResolvedPageTypeRoute],
    *,
    shared_props_model: type[BaseModel] | None,
) -> dict[str, list[JsonSchema]]:
    schemas: dict[str, list[JsonSchema]] = {}

    for route in routes:
        schema = _page_props_schema(
            props_model=route.props_model,
            shared_model=route.shared_model or shared_props_model,
        )
        entries = schemas.setdefault(route.component, [])
        if schema not in entries:
            entries.append(schema)

    return dict(sorted(schemas.items()))


def _page_props_schema(
    *,
    props_model: type[BaseModel] | None,
    shared_model: type[BaseModel] | None,
) -> JsonSchema:
    fields: dict[str, Any] = {}
    seen: dict[str, str] = {}

    def add(field: PagePropField, *, source: str) -> None:
        if existing_source := seen.get(field.key):
            msg = f'Inertia page prop "{field.key}" is declared by both {existing_source} and {source}'
            raise RuntimeError(msg)

        seen[field.key] = source
        default = ... if field.required else None
        fields[f"prop_{len(fields)}"] = (
            field.annotation,
            Field(
                default=default,
                alias=field.key,
                serialization_alias=field.key,
                validation_alias=field.key,
            ),
        )

    if props_model is not None:
        for field in _model_prop_fields(props_model, force_optional=False):
            add(field, source=props_model.__name__)

    if shared_model is not None:
        for field in _model_prop_fields(shared_model, force_optional=True):
            add(field, source=shared_model.__name__)

    add(
        PagePropField(
            annotation=dict[str, str | dict[str, str]],
            key="errors",
            required=True,
        ),
        source="Gdansk",
    )

    model = create_model(
        "GdanskGeneratedPageProps",
        __config__=ConfigDict(
            arbitrary_types_allowed=True,
            extra="forbid",
            populate_by_name=True,
        ),
        __module__=__name__,
        **fields,
    )
    schema = cast("JsonSchema", model.model_json_schema(by_alias=True, mode="serialization"))
    return _clean_schema(schema)


def _model_prop_fields(model: type[BaseModel], *, force_optional: bool) -> list[PagePropField]:
    fields: list[PagePropField] = []

    for field_name, model_field in model.model_fields.items():
        annotation = model_field.rebuild_annotation()
        required = not force_optional and model_field.is_required() and not _has_optional_payload_wrapper(annotation)
        fields.append(
            PagePropField(
                annotation=_field_payload_annotation(annotation),
                key=_model_field_prop_key(field_name, model_field),
                required=required,
            ),
        )

    return fields


def _field_payload_annotation(annotation: object) -> object:
    return _unwrap_prop_annotation(annotation)


def _unwrap_prop_annotation(annotation: object) -> object:
    annotated_args = _annotated_args(annotation)
    if annotated_args is not None:
        inner, _metadata = annotated_args
        unwrapped = _unwrap_prop_annotation(inner)
        return annotation if unwrapped is inner else unwrapped

    prop_args = _prop_generic_args(annotation)
    if prop_args:
        return prop_args[0]

    if _is_union_annotation(annotation):
        args = tuple(_unwrap_prop_annotation(arg) for arg in get_args(annotation))
        return _union_annotation(args)

    return annotation


def _has_optional_payload_wrapper(annotation: object) -> bool:
    annotation = _strip_annotated(annotation)
    origin = _prop_origin(annotation)
    if origin in {Defer, OptionalProp}:
        return True

    if _is_union_annotation(annotation):
        return any(_has_optional_payload_wrapper(arg) for arg in get_args(annotation))

    return False


def _prop_generic_args(annotation: object) -> tuple[object, ...]:
    metadata = getattr(annotation, "__pydantic_generic_metadata__", None)
    if not isinstance(metadata, dict):
        return ()

    if not _is_prop_origin(metadata.get("origin")):
        return ()

    args = metadata.get("args", ())
    return tuple(args) if isinstance(args, tuple) else ()


def _prop_origin(annotation: object) -> type[Prop[Any]] | None:
    metadata = getattr(annotation, "__pydantic_generic_metadata__", None)
    if not isinstance(metadata, dict):
        return None

    origin = metadata.get("origin")
    return cast("type[Prop[Any]]", origin) if _is_prop_origin(origin) else None


def _is_prop_origin(value: object) -> bool:
    return isinstance(value, type) and issubclass(value, Prop)


def _strip_annotated(annotation: object) -> object:
    while (annotated_args := _annotated_args(annotation)) is not None:
        annotation = annotated_args[0]

    return annotation


def _annotated_args(annotation: object) -> tuple[object, tuple[object, ...]] | None:
    if get_origin(annotation) is not Annotated:
        return None

    args = get_args(annotation)
    if not args:
        return None

    return args[0], args[1:]


def _is_union_annotation(annotation: object) -> bool:
    return get_origin(annotation) in {Union, UnionType}


def _union_annotation(args: Sequence[object]) -> object:
    clean_args = tuple(dict.fromkeys(args))
    if len(clean_args) == 0:
        return Any

    if len(clean_args) == 1:
        return clean_args[0]

    union = clean_args[0]
    for arg in clean_args[1:]:
        union = cast("type[Any]", union) | cast("type[Any]", arg)

    return union


def _model_field_prop_key(field_name: str, model_field: FieldInfo) -> str:
    alias = model_field.serialization_alias or model_field.alias
    return alias if isinstance(alias, str) else field_name


def _clean_schema(schema: JsonSchema) -> JsonSchema:
    cleaned = _clean_schema_value(schema)
    return cast("JsonSchema", cleaned)


def _clean_schema_value(value: object) -> object:
    if isinstance(value, dict):
        return {key: _clean_schema_value(item) for key, item in value.items() if key not in {"default", "title"}}

    if isinstance(value, list):
        return [_clean_schema_value(item) for item in value]

    return value


def _component_json_schema(schemas: Sequence[JsonSchema]) -> JsonSchema:
    if len(schemas) == 1:
        return schemas[0]

    return {"anyOf": list(schemas)}


def _component_ts_type(schemas: Sequence[JsonSchema]) -> str:
    types: list[str] = []
    for schema in schemas:
        ts_type = _schema_to_ts(schema, root=schema)
        if ts_type not in types:
            types.append(ts_type)

    return _join_ts_union(types)


def _schema_to_ts(schema: JsonSchema, *, root: JsonSchema, seen_refs: frozenset[str] = frozenset()) -> str:
    if ref_type := _schema_ref_to_ts(schema, root=root, seen_refs=seen_refs):
        return ref_type

    if literal_type := _schema_literal_to_ts(schema):
        return literal_type

    if composed_type := _schema_composition_to_ts(schema, root=root, seen_refs=seen_refs):
        return composed_type

    return _schema_type_to_ts(schema, root=root, seen_refs=seen_refs)


def _schema_ref_to_ts(schema: JsonSchema, *, root: JsonSchema, seen_refs: frozenset[str]) -> str | None:
    if ref := schema.get("$ref"):
        if not isinstance(ref, str) or ref in seen_refs:
            return "unknown"

        resolved = _resolve_ref(root=root, ref=ref)
        return _schema_to_ts(resolved, root=root, seen_refs=seen_refs | {ref})

    return None


def _schema_literal_to_ts(schema: JsonSchema) -> str | None:
    if "const" in schema:
        return _literal_ts(schema["const"])

    if isinstance(enum := schema.get("enum"), list):
        return _join_ts_union([_literal_ts(value) for value in enum])

    return None


def _schema_composition_to_ts(schema: JsonSchema, *, root: JsonSchema, seen_refs: frozenset[str]) -> str | None:
    for key in ("anyOf", "oneOf"):
        if isinstance(variants := schema.get(key), list):
            return _join_ts_types(
                [_schema_to_ts(_require_schema(variant), root=root, seen_refs=seen_refs) for variant in variants],
                mode="union",
            )

    if isinstance(variants := schema.get("allOf"), list):
        return _join_ts_types(
            [_schema_to_ts(_require_schema(variant), root=root, seen_refs=seen_refs) for variant in variants],
            mode="intersection",
        )

    return None


def _schema_type_to_ts(schema: JsonSchema, *, root: JsonSchema, seen_refs: frozenset[str]) -> str:
    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        child_types = [
            _schema_to_ts({**schema, "type": child_type}, root=root, seen_refs=seen_refs) for child_type in schema_type
        ]
        return _join_ts_union(child_types)

    if isinstance(schema_type, str):
        return _named_schema_type_to_ts(schema, schema_type=schema_type, root=root, seen_refs=seen_refs)

    return "unknown"


def _named_schema_type_to_ts(
    schema: JsonSchema,
    *,
    schema_type: str,
    root: JsonSchema,
    seen_refs: frozenset[str],
) -> str:
    if schema_type in {"string", "integer", "number", "boolean", "null"}:
        return _primitive_schema_type_to_ts(schema_type)

    if schema_type == "array":
        items = _require_schema(schema.get("items", {}))
        return f"Array<{_schema_to_ts(items, root=root, seen_refs=seen_refs)}>"

    if schema_type == "object":
        return _object_schema_to_ts(schema, root=root, seen_refs=seen_refs)

    return "unknown"


def _primitive_schema_type_to_ts(schema_type: str) -> str:
    if schema_type == "integer":
        return "number"

    if schema_type in {"string", "number", "boolean", "null"}:
        return schema_type

    return "unknown"


def _object_schema_to_ts(schema: JsonSchema, *, root: JsonSchema, seen_refs: frozenset[str]) -> str:
    properties = schema.get("properties")
    if isinstance(properties, dict):
        required = schema.get("required", [])
        required_keys = set(required) if isinstance(required, list) else set()
        lines = ["{"]

        for key, value in properties.items():
            prop_schema = _require_schema(value)
            optional = "" if key in required_keys else "?"
            ts_type = _schema_to_ts(prop_schema, root=root, seen_refs=seen_refs)
            lines.append(f"  {_ts_property_key(key)}{optional}: {ts_type};")

        lines.append("}")
        return "\n".join(lines)

    additional = schema.get("additionalProperties")
    if isinstance(additional, dict):
        return f"Record<string, {_schema_to_ts(additional, root=root, seen_refs=seen_refs)}>"

    if additional is False:
        return "{}"

    return "Record<string, unknown>"


def _require_schema(value: object) -> JsonSchema:
    return cast("JsonSchema", value) if isinstance(value, dict) else {}


def _resolve_ref(*, root: JsonSchema, ref: str) -> JsonSchema:
    if not ref.startswith("#/"):
        return {}

    resolved: object = root
    for raw_part in ref[2:].split("/"):
        part = raw_part.replace("~1", "/").replace("~0", "~")
        if not isinstance(resolved, dict):
            return {}
        resolved = resolved.get(part, {})

    return _require_schema(resolved)


def _join_ts_union(types: Sequence[str]) -> str:
    return _join_ts_types(types, mode="union")


def _join_ts_types(types: Sequence[str], *, mode: Literal["intersection", "union"]) -> str:
    unique = list(dict.fromkeys(types))
    if not unique:
        return "unknown"

    if len(unique) == 1:
        return unique[0]

    separator = " & " if mode == "intersection" else " | "
    return separator.join(unique)


def _literal_ts(value: object) -> str:
    if isinstance(value, str):
        return _json_string(value)

    if value is True:
        return "true"

    if value is False:
        return "false"

    if value is None:
        return "null"

    if isinstance(value, int | float):
        return str(value)

    return "unknown"


def _ts_property_key(key: str) -> str:
    if match(r"^[A-Za-z_$][A-Za-z0-9_$]*$", key) and key not in _TS_RESERVED_WORDS:
        return key

    return _json_string(key)


def _json_source(value: object) -> str:
    return dumps(value, ensure_ascii=False, indent=2, sort_keys=True)


def _json_string(value: str) -> str:
    return dumps(value, ensure_ascii=False)


__all__ = [
    "PageTypeRoute",
    "build_page_type_modules",
    "infer_page_props_model",
    "normalize_page_props_model",
    "write_page_type_modules",
]
