from typing import Generic, TypeVar

_I = TypeVar("_I")
_O = TypeVar("_O")

class Script(Generic[_I, _O]):
    def __init__(self, contents: str, inputs: object, outputs: object) -> None: ...
    @property
    def contents(self) -> str: ...
    @property
    def inputs(self) -> object: ...
    @property
    def outputs(self) -> object: ...

class Runtime:
    def __init__(self, *, dependencies: object | None = None) -> None: ...
    def __call__(self, script: Script[_I, _O], /) -> RuntimeContext[_I, _O]: ...

class RuntimeContext(Generic[_I, _O]):
    def __enter__(self) -> RuntimeContext[_I, _O]: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> None: ...
    def __call__(self, value: _I, /) -> _O: ...
