from os import PathLike
from typing import Self, overload

from pydantic import TypeAdapter

class Script[I, O]:
    @overload
    def __init__(
        self,
        contents: str,
        inputs: type[I],
        outputs: type[O],
    ) -> None: ...
    @overload
    def __init__(self, contents: str, inputs: object, outputs: object) -> None: ...
    @classmethod
    def from_file(
        cls: type[Self],
        path: str | PathLike[str],
        inputs: type[I],
        outputs: type[O],
    ) -> Self: ...
    @property
    def contents(self) -> str: ...
    @property
    def inputs(self) -> TypeAdapter[I]: ...
    @property
    def outputs(self) -> TypeAdapter[O]: ...

class Runtime:
    def __init__(self, *, package_json: str | PathLike[str] | None = None) -> None: ...
    def lock(self) -> None: ...
    async def alock(self) -> None: ...
    def sync(self) -> None: ...
    def __call__[I, O](self, script: Script[I, O], /) -> RuntimeContext[I, O]: ...

class RuntimeContext[I, O]:
    def __enter__(self) -> RuntimeContext[I, O]: ...
    async def __aenter__(self) -> AsyncRuntimeContext[I, O]: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> None: ...
    async def __aexit__(self, exc_type: object, exc_value: object, traceback: object) -> None: ...
    def __call__(self, value: I, /) -> O: ...

class AsyncRuntimeContext[I, O]:
    async def __call__(self, value: I, /) -> O: ...
