from typing import Self

class Script:
    def __new__(cls, contents: str) -> Self: ...
    def __init__(self, contents: str) -> None: ...
    @property
    def contents(self) -> str: ...

class Runtime:
    def __new__(cls, *, package_json: str | None = None) -> Self: ...
    def __init__(self, *, package_json: str | None = None) -> None: ...
    def lock(self) -> None: ...
    async def alock(self) -> None: ...
    def sync(self) -> None: ...

class RuntimeContext:
    def __new__(cls, contents: str, entry_path: str, root_path: str) -> Self: ...
    def __init__(self, contents: str, entry_path: str, root_path: str) -> None: ...
    def _ensure_inactive(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> None: ...
    def __call__(self, value: object, /) -> object: ...

class AsyncRuntimeContext:
    def __new__(cls, contents: str, entry_path: str, root_path: str) -> Self: ...
    def __init__(self, contents: str, entry_path: str, root_path: str) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type: object, exc_value: object, traceback: object) -> None: ...
    async def __call__(self, value: object, /) -> object: ...
