from os import PathLike
from typing import Self

from gdansk_runtime.script import Script

class Runtime:
    def __new__(cls, *, package_json: str | PathLike[str] | None = None) -> Self: ...
    def __init__(self, *, package_json: str | PathLike[str] | None = None) -> None: ...
    def lock(self) -> None: ...
    async def alock(self) -> None: ...
    def sync(self) -> None: ...
    def __call__[I, O](self, script: Script[I, O], /) -> RuntimeContext[I, O]: ...

class RuntimeContext[I, O]:
    def __new__(cls, script: Script[I, O], /) -> Self: ...
    def __init__(self, script: Script[I, O], /) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> None: ...
    async def __aenter__(self) -> AsyncRuntimeContext[I, O]: ...
    async def __aexit__(self, exc_type: object, exc_value: object, traceback: object) -> None: ...
    def __call__(self, value: I, /) -> O: ...

class AsyncRuntimeContext[I, O]:
    def __new__(cls, script: Script[I, O], /) -> Self: ...
    def __init__(self, script: Script[I, O], /) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type: object, exc_value: object, traceback: object) -> None: ...
    async def __call__(self, value: I, /) -> O: ...
