class LightningCssTransformer:
    def __init__(self, *, minify: bool = True) -> None: ...
    def transform(self, code: str, filename: str) -> str: ...

def transform_css(code: str, filename: str, *, minify: bool = True) -> str: ...
