import type { Plugin } from "vite";
import type { GdanskPluginOptions, LoadedProjectConfig, ResolvedGdanskOptions, WidgetDefinition } from "./types";
export declare function resolveOptions(options?: GdanskPluginOptions, configRoot?: string): ResolvedGdanskOptions;
export declare function discoverWidgets(options: ResolvedGdanskOptions): Promise<WidgetDefinition[]>;
export declare function ensureNoopEntry(options: ResolvedGdanskOptions): Promise<string>;
export declare function loadUserViteConfig(options: ResolvedGdanskOptions, command: "build" | "serve"): Promise<LoadedProjectConfig>;
export declare function prepareWidgets(options: ResolvedGdanskOptions): Promise<WidgetDefinition[]>;
export declare function loadProjectPlugins(options: ResolvedGdanskOptions): Promise<Plugin[]>;
export declare function pathExists(path: string): Promise<boolean>;
export declare function toPosixPath(path: string): string;
